config/routes.rb
Stronger::Application.routes.draw do

root :to => 'welcome#index'

resources :exercises
resources :workouts

  

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  attr_accessible :name, :primary_area, :secondary_area

  has_many :lifts

  has_many :workouts, through: :lifts

def name_for_select
	name.capitalize
end
  
end

app/models/lift.rb
class Lift < ActiveRecord::Base
  attr_accessible :reps, :sets, :weight, :id, :workout_id, :exercise_id

  belongs_to :exercise
  belongs_to :workout
  
end

app/models/workout.rb
class Workout < ActiveRecord::Base
   attr_accessible :id, :title, :body

  has_many :lifts

  has_many :exercises, through: :lifts

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

	def index
		@exercises = Exercise.all
	end

	def new
	end

	def create
		@exercise = Exercise.new(params[:exercise])

		@exercise.save
		redirect_to @exercise
	end

	def show 
		@exercise = Exercise.find(params[:id])
	end

	def destroy
		@exercise = Exercise.find(params[:id])

		@exercise.destroy
		redirect_to @exercise
	end

	def edit
		@exercise = Exercise.find(params[:id])
	end

	def update
		@exercise = Exercise.find(params[:id])

		if @exercise.update_attributes(params[:exercise])
			redirect_to @exercise
		else
			render 'edit'
		end
	end
		
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

def index
end

def new
	@workout = Workout.new
	@lift = Lift.new
end

def create
	@workout = Workout.new(params[:workout])
	@workout.save

	@lift = Lift.new(params[:lift])
	@lift.workout_id = @workout.id
	@lift.save

	redirect_to @workout
end

def show
	@workout = Workout.find(params[:id])

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/edit.html.erb
<div class="container">
	<h1>Edit Exercise</h1>
</div>

<div class="container">
	<%= form_for :exercise, url: exercise_path(@exercise), method: :put do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
		<%= f.label :primary_area %><br>
		<%= f.select :primary_area, options_for_select(["Front", "Back", "Lower", "Full Body"]) %><br>
		<%= f.label :secondary_area %><br>
		<%= f.select :secondary_area, options_for_select(["Chest", "Abs", "Shoulders", "Biceps", "Triceps", "Upper Back", "Lower Back", "Glutes", "Quads"])%><br>
	</p>
	<%= f.submit %>
	<% end %>
</div>
<%= link_to 'Back', exercise_path %>

app/views/exercises/index.html.erb
<div class="container">
	<h1>My Exercises</h1>
</div>

<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Primary Muscle Area</th>
				<th>Secondary Muscle Area</th>
				<th colspan="2"></th>
			</tr>
		</thead>
		<tbody>
			<% @exercises.each do |d|%>
			<tr>
				<td><%= d.name %></td>
				<td><%= d.primary_area %></td>
				<td><%= d.secondary_area %></td>
				<td><%= link_to 'Edit', edit_exercise_path(d) %></td>
				<td><%= link_to 'Destroy', exercise_path(d), method: :delete, data: {confirm: 'Are you sure?'} %></td>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>

<div class="container">
	<a href=/exercises/new class="btn btn-primary" role="button">New Exercise</a>
</div>

app/views/exercises/new.html.erb
<div class="container">
	<h1>New Exercise</h1>
</div>

<div class="container">
	<%= form_for :exercise, url: exercises_path do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
		<%= f.label :primary_area %><br>
		<%= f.select :primary_area, options_for_select(["Front", "Back", "Lower", "Full Body"]) %><br>
		<%= f.label :secondary_area %><br>
		<%= f.select :secondary_area, options_for_select(["Chest", "Abs", "Shoulders", "Biceps", "Triceps", "Upper Back", "Lower Back", "Glutes", "Quads"])%><br>
	</p>
	<%= f.submit %>
	<% end %>
</div>

app/views/exercises/show.html.erb
<div class="container">
	<h1><%= @exercise.name %></h1>
</div>
<div class="container">
	<p>Primary Area: <%= @exercise.primary_area %><br>
		Secondary Area: <%= @exercise.secondary_area %><br>
	</p>
</div>

<div class="container">
	<%= link_to 'All Exercises', controller: 'exercises' %>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" <%= link_to 'Stronger', controller: 'welcome' %>
		</div>
	<div>
	<ul class="nav navbar-nav navbar-right">
		<li><%= link_to 'Home', controller: 'welcome' %></li>
		<li><%#= link_to 'Analysis', controller: XXX %></li>
		<li> <%= link_to 'Exercises', controller: 'exercises' %></li>
	</ul>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stronger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header"%>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h1> Stronger</h1>
		<p>Log yr Gainz </p>
	</div>
</div>

<div class="container">
	<a href=workouts/new class="btn btn-primary" role="button">New Workout</a>
	<a href=# class="btn btn-primary" role="button">Analysis</a>
	<a href=/exercises class="btn btn-primary" role="button">Exercises</a>
</div>

app/views/workouts/index.html.erb
insert log here

app/views/workouts/new.html.erb
<div class="container">
	<h1>New Workout</h1>
</div>

<div class="container">
	<%= form_for :lift, url: workouts_path do |f| %>
	<p>Exercise Name: <br>
		<%= f.collection_select(:exercise_id, Exercise.all, :id, :name_for_select) %>
	</p>
	<p>Sets: <%= f.select :sets, options_for_select( (1..10).step(1)) %></p>
	<p>Reps: <%=f.select :reps, options_for_select( (1..60).step(1)) %></p>
	<p>Weight: <%= f.select :weight, options_for_select( (10..250).step(5))%></p>
	<%= f.submit "Submit", class: "btn-btn-info" %>
	<% end %>
</div>

app/views/workouts/show.html.erb
<h1> Workout Number <%= @workout.id %></h1>

<div class="container">
	<table class="table table-striped">
		<thead>
			<th>Excercize</th>
			<th>Sets</th>
			<th>Reps</th>
			<th>Weight</th>
		</thead>
		<tbody>
			<% @workout.exercises.each do |e| %>
			<% @workout.lifts.each do |w| %>
			<tr>
				<td> <%= e.name %></td>
				<td><%= w.sets %></td>
				<td><%= w.reps %></td>
				<td><%= w.weight %></td>
			</tr>
		</tbody>
		<% end %>
		<% end %>
	</table>
</div>